name: b_smart
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lucide_icons_flutter: ^3.1.9

  # Auth & Backend
  jwt_decoder: ^2.0.1
  crypto: ^3.0.3
  flutter_secure_storage: ^9.2.2
  http: ^1.2.1
  webview_flutter: ^4.8.0
  webview_flutter_android: 4.10.11 # Pinned to avoid build error in 4.10.13
  flutter_web_auth_2: ^4.0.0

  # Device Info
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.2

  # Google Sign In (Native)
  google_sign_in: ^6.1.6

  # Utilities
  intl: ^0.19.0
  video_player: ^2.8.2
  flutter_dotenv: ^5.1.0
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  firebase_messaging: ^14.7.10
  image_picker: ^1.1.2
  image_cropper: ^11.0.0
  meta: ^1.11.0
  path: ^1.9.0
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  preload_page_view: ^0.2.0
  flutter_svg: ^2.0.10
  camera: ^0.10.5+5
  permission_handler: ^11.3.1
  flutter_image_compress: ^2.2.0
  photo_manager: ^3.0.0
  geolocator: ^10.1.0
  geocoding: ^2.2.0
  video_thumbnail: ^0.5.3
  visibility_detector: ^0.4.0+2
  extended_image: ^8.2.1

  # Stable compatible versions
  insta_assets_picker: ^3.4.0
  wechat_assets_picker: ^9.8.0
  pro_image_editor: ^9.2.0

  flutter_colorpicker: ^1.1.0
  google_fonts: ^6.1.0

  # ✅ Stable FFmpeg (LAST PUBLIC WORKING VERSION)
  ffmpeg_kit_flutter_new: ^4.1.0

  http_parser: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Lucide
      fonts:
        - asset: assets/fonts/lucide.ttf

  assets:
    - assets/images/dashboard_sample.png
    - assets/images/logo.svg
    - assets/images/google_logo.svg
    - .env
